# -*- Mode: python -*-

import os
import sys

symlink_builder = Builder(action = 'ln -sf $SOURCE $TARGET')

env = Environment()

env.Append(BUILDERS = {"Symlink": symlink_builder})

env.Symlink("pexpect.py", "../pexpect.py")
